# Generated by Django 2.0 on 2017-12-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=150)),
                ('item_name', models.CharField(max_length=150)),
                ('item_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('item_quantity', models.IntegerField()),
                ('stock_arrival_date', models.DateField()),
                ('min_stock', models.IntegerField()),
                ('max_stock', models.IntegerField()),
                ('staff_check', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Inventory item',
                'verbose_name_plural': 'Inventory items',
            },
        ),
    ]
